theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "WD Dev"
description: "Enjoy Application Developement!"
baseurl: "" # the subpath of your site, e.g. "/blog"
url: "https://dev-wd.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/logo.png" # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
 paginate: 10
 paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
 category_archive_path: "/categories/#"
 tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true


# Site Author
author:
  name: Liam SY Kim
  picture: /images/profile.jpeg
  email: dldl8675@gmail.com
  links:
    - title: GitHub
      url: https://github.com/dev-wd
      icon: fab fa-github-square
    - title: Instagram
      url: https://www.instagram.com/wd______/
      icon: fab fa-instagram

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/dev-wd
    icon: fab fa-github-square
  - title: Instagram
    url: https://www.instagram.com/wd______/
    icon: fab fa-instagram
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

remote_theme : mmistakes/so-simple-theme
